### ISSUE TITLE
dependencies: sesshim, bootbnf

### ISSUE THREAD

**Issue by dckc** [Agoric/TinySES#3]
where does one get these?

```
  const {def} = require('../../src/sesshim.js');
  const {bnf} = require('../../src/bootbnf.js');
```

**Comment by erights** [comment]
Sorry for the confusion.
https://github.com/erights/quasiParserGenerator

**Comment by dckc** [comment]
here's all the relevant files zip'd up.

[jessie.zip](https://github.com/Agoric/Jessie/files/3839189/jessie.zip)

also available as https://repl.it/@dckc/jessie-safe-mobile-code
