### ISSUE TITLE
params and ()s

### ISSUE THREAD

**Issue by dckc** [Agoric/TinySES#6]
The definition of params already includes the ()s, but they appear again in the productions for functionExpr, functionDecl, etc.

Surely that's not on purpose.

https://github.com/Agoric/TinySES/blob/92f6766a1a392b82f85f5d4dc89f53f73ce4dee9/src/tinyses.js#L285

**Comment by erights** [comment]
Thanks for catching this! Your PR has the right fix, but see the review comments.
